# Generated by Django 5.2.4 on 2025-07-13 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('needs', '0002_remove_needs_price_max_remove_needs_price_min_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='needs',
            old_name='price',
            new_name='price_max',
        ),
        migrations.AddField(
            model_name='needs',
            name='capacity',
            field=models.TextField(default=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='needs',
            name='price_min',
            field=models.DecimalField(decimal_places=2, default=50.23, max_digits=10),
            preserve_default=False,
        ),
    ]
